### ISSUE TITLE
oh no, no Polish characters in the fancy font

### ISSUE THREAD

**Issue by WitchDevelops** [WitchDevelops/cardboard-fort#37]
![image](https://github.com/WitchDevelops/cardboard-fort/assets/112077394/b57e7494-1123-41b4-ae85-ee0b1f8e7cb4)

Figure out why, font face is Fredoka iirc and it's from Google.
Probably some setup issues in Next/fonts or something like that

**Comment by WitchDevelops** [comment]
Fredokka does not support Polish characters.
https://fonts.google.com/specimen/Fredoka/glyphs?preview.text=%C4%85%C4%85%C4%85%C4%87%C5%BA%C5%BC%C4%85%C5%82%C3%B3goddam%20it

**Comment by WitchDevelops** [comment]
Chewy (originally used in the Figma desing) also does not support polish characters.

**Comment by WitchDevelops** [comment]
My suggestions:
- [varela round](https://fonts.google.com/specimen/Varela+Round?preview.text=%C5%BB%C3%B3%C5%82wik%20Pi%C4%85tek)
- [Mitr](https://fonts.google.com/specimen/Mitr?preview.text=%C5%BB%C3%B3%C5%82wik%20K%C4%85tek%20Mi%C4%99tek)
- [RedHat display](https://fonts.google.com/specimen/Red+Hat+Display?preview.text=Pi%C4%85tek%20%C5%9Ani%C4%85tek)

**Comment by jagodakubicka** [comment]
Coiny looks best :)
